# Generated by Django 3.0 on 2019-12-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='obat',
            name='kandungan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='obat',
            name='khasiat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pasien',
            name='keluhan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resep',
            name='kumpulan_obat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resep',
            name='total_harga',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='bidang',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='nomor_telepon',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_telepon',
            field=models.CharField(default='', max_length=15),
        ),
    ]
