# Generated by Django 3.0 on 2019-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20191209_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.DateTimeField(verbose_name='Jadwal Praktek'),
        ),
    ]
