# Generated by Django 3.0 on 2019-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0002_auto_20191209_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='hari_berkunjung',
            field=models.DateField(auto_now=True, verbose_name='Jadwal Berkunjung'),
        ),
        migrations.AlterField(
            model_name='penjaga',
            name='jadwal_jaga',
            field=models.DateField(auto_now=True, verbose_name='Jadwal Jaga'),
        ),
    ]
