# Generated by Django 3.0 on 2019-12-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=40)),
                ('no_telepon', models.CharField(default='', max_length=15)),
                ('jabatan', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=20)),
                ('jadwal_dimulai', models.TimeField(verbose_name='Jadwal Dimulai')),
                ('jadwal_berakhir', models.TimeField(verbose_name='Jadwal Berakhir')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=40)),
                ('no_telepon', models.CharField(default='', max_length=15)),
                ('nomor_absen', models.IntegerField(default=0)),
                ('nilai_rata2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=40)),
                ('no_telepon', models.CharField(default='', max_length=15)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ata.MataPelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='LiveCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=20)),
                ('banyak_soal', models.IntegerField(default=0)),
                ('bobot_nilai', models.FloatField(default=0)),
                ('tanggal_pelaksanaan', models.DateTimeField(verbose_name='Tanggal Pelaksanaan')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ata.MataPelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=20)),
                ('banyak_soal', models.IntegerField(default=0)),
                ('bobot_nilai', models.FloatField(default=0)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ata.MataPelajaran')),
            ],
        ),
    ]
